[package]
name = "server"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0"
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rcgen = { version = "0.11", features = ["pem"] }
portable-pty = "0.8"
futures = "0.3"
shared = { path = "../shared" }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
subtle = "2.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
aya = { version = "0.13", features = ["async_tokio"] }
gateway-ebpf-common = { path = "../gateway-ebpf-common", features = ["user"] }
bytes = "1"
